Fix/district features
map-yemen/map-yemen.github.io pull request #12
Opened 2017-03-06 19:13 UTC by DylanMoriarty

Fixes the search bar, updates the about text, & modifies the charts to resize based on how long the data is.

2017-03-07 21:36 UTC, felskia reviewed
@DylanMoriarty can you get rid of the space at the top and bottom of the charts?

2017-03-08 19:44 UTC, nbumbarger commented
I left one inline comment, but a second issue is that the search bar doesn't function as I think it should: the only way to navigate is by typing in a governorate name, then clicking one of the entries in the autocomplete dropdown menu. The search button and enter keys don't work.
The icon should be given an `onClick` event listener that triggers the `zoomToGovernorate` function, and the search bar can be given an `onKeyPress` or `onKeyDown` event that listens for key #13 (the enter key), e.g. 
```
const handleEnter = (e) => {
  if (e.keyCode === 13)...
}
```

2017-03-08 19:44 UTC, nbumbarger requested changes
I left one inline comment, but a second issue is that the search bar doesn't function as I think it should: the only way to navigate is by typing in a governorate name, then clicking one of the entries in the autocomplete dropdown menu. The search button and enter keys don't work.
The icon should be given an `onClick` event listener that triggers the `zoomToGovernorate` function, and the search bar can be given an `onKeyPress` or `onKeyDown` event that listens for key #13 (the enter key), e.g. 
```
const handleEnter = (e) => {
  if (e.keyCode === 13)...
}
```

2017-03-08 19:44 UTC, nbumbarger commented on app/assets/scripts/components/charts/horizontal-bar.js
> +    if (innerWidth <= 0) {
I don't think that it's practically possible to meet this condition

2017-03-08 20:55 UTC, DylanMoriarty commented on app/assets/scripts/components/charts/horizontal-bar.js
> +    if (innerWidth <= 0) {
For some reason when you initially toggle out to the chart view, the value here goes negative from the margin values used to calculate innerWidth earlier, and it breaks the load. 

I looked into what was causing the issue, but having this condition seems to work & appears to be the solution used for Map Egypt as well.

2017-03-08 22:33 UTC, merged